/**
 * YuePopover design interview.
 * The panel template loads this file without a bundler.
 */

window.COMPONENT_NAME = 'YuePopover';
window.SCHEMA_VERSION = 2;
window.TEMPLATE_VERSION = '2.0.0';
window.FINDINGS = [
  {
    id: 'finding-floating-ui-adapters',
    topic: '@floating-ui/dom 与 @floating-ui/vue',
    finding: '@floating-ui/dom 提供框架无关的定位核心；@floating-ui/vue 是 Vue 适配层。Yue 已有 hooks、Teleport、ARIA 与生命周期边界，因此只把 dom 核心作为内部依赖，不向消费者暴露 Floating UI 类型。',
    sources: ['refer/floating-ui-master', 'Popover spec research'],
    confidence: 'high',
    leadsTo: [33, 39, 40],
    round: 6,
  },
];

window.SECTIONS = [
  { title: '第一轮：组件定义与边界', start: 1, end: 8 },
  { title: '第二轮：API 与交互模型', start: 9, end: 17 },
  { title: '第三轮：定位、可访问性与非功能项', start: 18, end: 27 },
  { title: '第四轮：冲突决策确认', start: 28, end: 34 },
  { title: '第五轮：定位方案与规格冻结', start: 35, end: 38 },
  { title: '第六轮：Vue 适配器选择', start: 39, end: 40 },
];

window.QUESTIONS = [
  {
    id: 1,
    round: 1,
    summary: '核心场景',
    question: 'YuePopover 首要解决哪类问题？',
    options: [
      { letter: 'A', text: '在触发控件附近展示补充内容或操作', recommended: true },
      { letter: 'B', text: '承载必须完成的模态流程或表单', recommended: false },
      { letter: 'C', text: '展示纯说明性的悬浮提示', recommended: false },
      { letter: 'D', text: '作为所有菜单、选择器、对话框的统一容器', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 2,
    round: 1,
    summary: '驱动方式',
    question: '组件应如何被创建和使用？',
    options: [
      { letter: 'A', text: 'template 驱动：通过 YuePopover 在模板中声明', recommended: true },
      { letter: 'B', text: 'imperative 驱动：通过 JS API 动态创建实例', recommended: false },
      { letter: 'C', text: '两者同时提供，先实现 imperative API', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 3,
    round: 1,
    summary: '组合关系',
    question: 'Popover 的第一版组合模型是什么？',
    options: [
      { letter: 'A', text: 'atomic：一个组件通过 trigger/content 插槽完成', recommended: true },
      { letter: 'B', text: 'compound：Popover、Trigger、Content、Arrow 分成多个公开组件', recommended: false },
      { letter: 'C', text: '同时公开 atomic 简写和 compound 原语', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 4,
    round: 1,
    summary: '生命周期',
    question: '默认生命周期应属于哪一类？',
    options: [
      { letter: 'A', text: 'transient：关闭后销毁内容，适合轻量浮层', recommended: true },
      { letter: 'B', text: 'persistent：首次打开后保留内容状态', recommended: false },
      { letter: 'C', text: '由 persistent prop 显式选择，默认不设定', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 5,
    round: 1,
    summary: '内容范围',
    question: 'Popover 内容是否允许包含复杂交互控件？',
    options: [
      { letter: 'A', text: '允许，Popover 只负责浮层容器和交互边界', recommended: true },
      { letter: 'B', text: '只允许静态文本和简单按钮', recommended: false },
      { letter: 'C', text: '不限制，但复杂内容必须改用 Dialog', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 6,
    round: 1,
    summary: '与组件边界',
    question: '哪些行为应该明确留给后续专用组件，而不是放进 Popover？',
    options: [
      { letter: 'A', text: '菜单方向键导航与 roving tabindex', recommended: true },
      { letter: 'B', text: '焦点管理、Escape 和 outside pointer 基础行为', recommended: false },
      { letter: 'C', text: '模态遮罩、focus trap 和强制初始焦点', recommended: true },
      { letter: 'D', text: '定位、碰撞翻转和滚动重定位', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 7,
    round: 1,
    summary: '组件定位',
    question: 'Popover 在 Yue 组件族中的定位是什么？',
    options: [
      { letter: 'A', text: '基础 detached overlay primitive，供 Menu、Select、DatePicker 等复用', recommended: true },
      { letter: 'B', text: '只服务于一个具体业务场景，不作为基础层', recommended: false },
      { letter: 'C', text: '直接等同于 Dialog 的非模态别名', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 8,
    round: 1,
    summary: '首版非目标',
    question: '为了控制首版范围，哪些能力可以暂不实现？',
    options: [
      { letter: 'A', text: '箭头装饰与自定义箭头形状', recommended: true },
      { letter: 'B', text: '基础 placement、碰撞处理与 Escape 关闭', recommended: false },
      { letter: 'C', text: '复杂动画编排和弹簧物理效果', recommended: true },
      { letter: 'D', text: '嵌套浮层的层级协调', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 9,
    round: 2,
    summary: 'open ownership',
    question: 'open 状态采用什么模型？',
    options: [
      { letter: 'A', text: '受控与非受控并存：modelValue 作为受控入口，默认内部管理', recommended: true },
      { letter: 'B', text: '只允许受控，必须由父级传入 modelValue', recommended: false },
      { letter: 'C', text: '只允许非受控，通过 ref 暴露 open/close', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 10,
    round: 2,
    summary: '触发方式',
    question: '默认触发方式和可选触发方式是什么？',
    options: [
      { letter: 'A', text: '默认 click，可选 hover、focus、manual', recommended: true },
      { letter: 'B', text: '默认 hover，可选 click、focus、manual', recommended: false },
      { letter: 'C', text: '只支持 click，其他行为交给调用方', recommended: false },
      { letter: 'D', text: '同时监听 click、hover、focus，不提供选择', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 11,
    round: 2,
    summary: '无触发器',
    question: '是否允许 Popover 没有内置 trigger，而由外部控制 anchor？',
    options: [
      { letter: 'A', text: '允许，通过 reference/anchor 插槽或显式 anchor 元素使用', recommended: true },
      { letter: 'B', text: '不允许，必须渲染默认 trigger 插槽', recommended: false },
      { letter: 'C', text: '只允许 imperative API 指定 anchor', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 12,
    round: 2,
    summary: '关闭事件',
    question: '哪些行为应默认关闭浮层？',
    options: [
      { letter: 'A', text: 'Escape', recommended: true },
      { letter: 'B', text: '点击浮层外部的 pointerdown', recommended: true },
      { letter: 'C', text: '点击浮层内容内部任意位置', recommended: false },
      { letter: 'D', text: 'trigger 再次点击（toggle）', recommended: true },
    ],
    recommended: 'A',
  },
  {
    id: 13,
    round: 2,
    summary: '关闭原因',
    question: '关闭时是否需要向消费者暴露稳定的 close reason？',
    options: [
      { letter: 'A', text: '需要：escape、outside、trigger、programmatic 等原因', recommended: true },
      { letter: 'B', text: '不需要，消费者只关心 update:modelValue', recommended: false },
      { letter: 'C', text: '只暴露 boolean，不暴露事件来源', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 14,
    round: 2,
    summary: '定位 API',
    question: 'placement 应支持到什么粒度？',
    options: [
      { letter: 'A', text: 'top、bottom、left、right 加 start/end 对齐', recommended: true },
      { letter: 'B', text: '只支持 top/bottom 四个固定方向', recommended: false },
      { letter: 'C', text: '接受任意 CSS position 值，由组件直接拼接', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 15,
    round: 2,
    summary: '碰撞策略',
    question: '当首选位置超出视口时，组件应如何处理？',
    options: [
      { letter: 'A', text: '自动 flip 到相反方向，并在必要时 shift 保持可见', recommended: true },
      { letter: 'B', text: '保持原位，允许内容超出视口', recommended: false },
      { letter: 'C', text: '由消费者监听事件后自行修改 placement', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 16,
    round: 2,
    summary: 'Teleport',
    question: '浮层内容默认渲染到哪里？',
    options: [
      { letter: 'A', text: 'Teleport 到 document.body，提供 to/disabled 覆盖入口', recommended: true },
      { letter: 'B', text: '始终留在 trigger 的 DOM 子树中', recommended: false },
      { letter: 'C', text: '默认 Teleport 到专用全局 overlay root，若不存在则创建', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 17,
    round: 2,
    summary: '内容点击',
    question: '点击 content 内部后，Popover 的默认行为是什么？',
    options: [
      { letter: 'A', text: '保持打开，只有显式 close 或外部行为才关闭', recommended: true },
      { letter: 'B', text: '立即关闭，模拟菜单选择行为', recommended: false },
      { letter: 'C', text: '由 closeOnContentClick prop 决定，默认关闭', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 18,
    round: 3,
    summary: '焦点进入',
    question: '打开后焦点应如何处理？',
    options: [
      { letter: 'A', text: '默认不强制移动焦点，允许内容中的自然 focus 顺序', recommended: true },
      { letter: 'B', text: '自动移动到 content 第一个可聚焦元素', recommended: false },
      { letter: 'C', text: '自动启用 focus trap', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 19,
    round: 3,
    summary: '焦点恢复',
    question: '关闭后是否恢复 trigger 焦点？',
    options: [
      { letter: 'A', text: '默认恢复，但仅当 trigger 仍在文档且未被禁用', recommended: true },
      { letter: 'B', text: '从不恢复，完全交给调用方', recommended: false },
      { letter: 'C', text: '所有关闭原因都强制恢复，即使用户已移动焦点', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 20,
    round: 3,
    summary: 'ARIA 语义',
    question: 'Popover 的默认 ARIA 角色和关联方式是什么？',
    options: [
      { letter: 'A', text: 'content 默认 role="dialog"，trigger 使用 aria-controls/expanded', recommended: true },
      { letter: 'B', text: 'content 默认 role="tooltip"', recommended: false },
      { letter: 'C', text: '组件不设置 role，完全由调用方负责', recommended: false },
      { letter: 'D', text: '根据 trigger 类型自动切换 dialog/menu/tooltip 三种角色', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 21,
    round: 3,
    summary: '键盘行为',
    question: 'Popover 本身应承诺哪些键盘行为？',
    options: [
      { letter: 'A', text: 'Escape 关闭并恢复焦点', recommended: true },
      { letter: 'B', text: 'Tab 由浏览器自然流动，不实现焦点陷阱', recommended: true },
      { letter: 'C', text: '方向键在任意内容中移动选中项', recommended: false },
      { letter: 'D', text: 'Enter/Space 由 trigger 原生语义处理', recommended: true },
    ],
    recommended: 'A',
  },
  {
    id: 22,
    round: 3,
    summary: '滚动重定位',
    question: 'anchor 或视口滚动、resize 时应如何处理？',
    options: [
      { letter: 'A', text: '监听并节流重定位，关闭/卸载时清理监听', recommended: true },
      { letter: 'B', text: '不重定位，等待下一次打开', recommended: false },
      { letter: 'C', text: '只在消费者手动调用 updatePosition 时重定位', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 23,
    round: 3,
    summary: 'SSR 安全',
    question: 'SSR、hydration 和无 document 环境需要什么保证？',
    options: [
      { letter: 'A', text: '服务端不读取浏览器对象；id 稳定且 hydration 不产生结构差异', recommended: true },
      { letter: 'B', text: '组件只允许在客户端渲染', recommended: false },
      { letter: 'C', text: '服务端生成随机 id，客户端打开时再替换', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 24,
    round: 3,
    summary: '动效与无障碍',
    question: 'Popover 动效和 reduced-motion 应如何约定？',
    options: [
      { letter: 'A', text: '短时淡入/位移动效；prefers-reduced-motion 时禁用非必要动画', recommended: true },
      { letter: 'B', text: '不提供任何动效或过渡', recommended: false },
      { letter: 'C', text: '始终使用弹簧动画，不响应系统偏好', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 25,
    round: 3,
    summary: '嵌套与层级',
    question: '嵌套 Popover 或与其他 overlay 共存时，层级和 outside 事件如何处理？',
    options: [
      { letter: 'A', text: '按打开顺序管理层级；点击子浮层不关闭其父浮层', recommended: true },
      { letter: 'B', text: '所有浮层固定同一个 z-index，嵌套不特殊处理', recommended: false },
      { letter: 'C', text: '打开子浮层时始终关闭父浮层', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 26,
    round: 3,
    summary: '实现基础',
    question: '定位和焦点基础能力应如何实现？',
    options: [
      { letter: 'A', text: '复用项目已有或选定的 floating/focus 实现，不手写第二套算法', recommended: true },
      { letter: 'B', text: '为 Popover 单独手写定位和 focus trap，便于快速控制', recommended: false },
      { letter: 'C', text: '首版不做碰撞和焦点行为，后续再补', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 27,
    round: 3,
    summary: '验收重点',
    question: '首版验收时哪些证据是必需的？',
    options: [
      { letter: 'A', text: '真实浏览器几何：placement、flip/shift、Teleport、滚动和 resize', recommended: true },
      { letter: 'B', text: '真实浏览器交互：outside、Escape、焦点恢复、嵌套层级', recommended: true },
      { letter: 'C', text: '只要 jsdom 单测覆盖 props 就足够', recommended: false },
      { letter: 'D', text: 'SSR/renderToString、类型、文档和导出门禁', recommended: true },
    ],
    recommended: 'A',
  },
  {
    id: 28,
    round: 4,
    summary: '共享边界',
    question: 'Popover 与 Menu、Select、Tooltip、Dialog 的关系应如何设计？',
    options: [
      { letter: 'A', text: 'Popover 只提供共享 overlay 基础；专用组件复用内部 composables，不把所有语义塞进 Popover', recommended: true },
      { letter: 'B', text: 'Popover 直接成为所有浮层的公开统一组件，内部根据 props 切换 menu/dialog/tooltip 语义', recommended: false },
      { letter: 'C', text: '每个组件完全独立实现，不共享定位、层级、outside、焦点逻辑', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 29,
    round: 4,
    summary: '公开组合',
    question: '首版是否公开 compound 子组件和 imperative API？',
    options: [
      { letter: 'A', text: '不公开；先提供 template 组件、slots、v-model 和 expose 的 open/close/updatePosition', recommended: true },
      { letter: 'B', text: '公开 YuePopoverTrigger/YuePopoverContent/YuePopoverArrow 等 compound 子组件', recommended: false },
      { letter: 'C', text: '同时公开 compound 子组件与全局 imperative create/open API', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 30,
    round: 4,
    summary: '默认生命周期',
    question: '首版默认 lifecycle 选择哪一个？',
    options: [
      { letter: 'A', text: 'transient：关闭后销毁内容；persistent 作为显式 prop', recommended: true },
      { letter: 'B', text: 'persistent：首次打开后保留内容状态；destroyOnClose 作为显式 prop', recommended: false },
      { letter: 'C', text: '不设默认，必须由调用方明确选择', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 31,
    round: 4,
    summary: '首版范围',
    question: '“都实现”应如何落到首版范围？',
    options: [
      { letter: 'A', text: '首版实现基础 click/focus/hover/manual、placement、flip/shift、Teleport、outside、Escape、嵌套层级和焦点恢复；不实现菜单导航与 Dialog focus trap', recommended: true },
      { letter: 'B', text: '首版把菜单导航、Dialog focus trap、模态遮罩也纳入 Popover', recommended: false },
      { letter: 'C', text: '先只实现 click + 基础 placement，其余全部后续迭代', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 32,
    round: 4,
    summary: 'ARIA 角色',
    question: '通用 Popover 的默认 ARIA 语义应如何处理？',
    options: [
      { letter: 'A', text: '默认 role="dialog" 仅适用于可交互内容；提供 role prop，Tooltip/Menu 等专用组件覆盖自己的语义', recommended: true },
      { letter: 'B', text: '始终 role="dialog"，所有专用组件也复用该角色', recommended: false },
      { letter: 'C', text: '默认不设置 role，所有语义完全交给调用方', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 33,
    round: 4,
    type: 'fact-question',
    required: true,
    introducedBy: 'user-question-1',
    summary: '定位依赖',
    question: '定位算法的实现策略是什么？',
    options: [],
    recommended: [],
  },
  {
    id: 34,
    round: 4,
    summary: '确认方式',
    question: '本轮答案确认后，是否冻结规格并进入设计阶段？',
    options: [
      { letter: 'A', text: '确认；先生成 spec.md 与 API/Token/验证契约，确认后再写实现', recommended: true },
      { letter: 'B', text: '先写一个原型，看到效果后再决定 API', recommended: false },
      { letter: 'C', text: '直接开始实现，规格在开发中补齐', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 35,
    round: 5,
    summary: '定位方案',
    question: '结合 ChengJing 手写定位、Vuetify composables 和 Floating UI 源码，Popover 首版采用哪种定位基础？',
    options: [
      { letter: 'A', text: '引入 @floating-ui/dom；在 Yue hooks 封装 computePosition/flip/shift/size/autoUpdate，不复制几何算法', recommended: true },
      { letter: 'B', text: '复用 ChengJing 的 checkFit/calculateCoords，继续扩展为通用定位引擎', recommended: false },
      { letter: 'C', text: '在 Yue 内部从零实现完整定位引擎，再自行覆盖滚动容器、RTL、裁剪祖先和动态尺寸', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 36,
    round: 5,
    summary: '依赖边界',
    question: '引入定位依赖时，公开 API 和依赖边界如何处理？',
    options: [
      { letter: 'A', text: 'Floating UI 作为 @yue-ui/vue 的内部 runtime dependency，不向消费者暴露其类型；Yue API 使用自己的 Placement 类型', recommended: true },
      { letter: 'B', text: '直接 re-export Floating UI 的类型和 middleware，让消费者完全控制定位', recommended: false },
      { letter: 'C', text: '不接受运行时依赖，所有能力必须由 Yue 自己实现', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 37,
    round: 5,
    summary: '共享实现',
    question: '未来 Menu、Select、Tooltip、Dialog 应如何复用 Popover 相关能力？',
    options: [
      { letter: 'A', text: '抽取无语义的 hooks/composables（定位、stack、outside、focus restore、Teleport）；各公开组件自己定义语义和键盘模式', recommended: true },
      { letter: 'B', text: '所有组件直接嵌套 YuePopover，通过 props 切换语义', recommended: false },
      { letter: 'C', text: '每个组件独立实现，避免共享抽象', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 38,
    round: 5,
    summary: '最终冻结',
    question: '若选择 35–37 的推荐方案，是否确认生成 spec.md 并冻结 API，随后进入 yue-component-design？',
    options: [
      { letter: 'A', text: '确认冻结；规格必须记录引入依赖、公开边界和所有验收门禁', recommended: true },
      { letter: 'B', text: '不确认，先做一个定位原型再决定', recommended: false },
      { letter: 'C', text: '不确认，继续扩大访谈范围', recommended: false },
    ],
    recommended: 'A',
  },
  {
    id: 39,
    round: 6,
    type: 'fact-question',
    required: true,
    introducedBy: 'user-question-2',
    summary: 'DOM 与 Vue',
    question: '@floating-ui/dom 与 @floating-ui/vue 的主要差异是什么？',
    options: [],
    recommended: [],
  },
  {
    id: 40,
    round: 6,
    summary: 'Vue 适配策略',
    question: '考虑 Yue 只支持 Vue 3、已有 hooks 层且需要自己管理 open/Teleport/ARIA/focus 生命周期，定位层应选什么？',
    options: [
      { letter: 'A', text: '直接依赖 @floating-ui/dom；在 Yue hooks 中封装 Vue 3 响应式和组件语义，避免 vue-demi 与第二套生命周期抽象', recommended: true },
      { letter: 'B', text: '依赖 @floating-ui/vue，并直接把 useFloating 的返回值暴露给 Yue 消费者', recommended: false },
      { letter: 'C', text: '同时依赖 @floating-ui/vue 和 @floating-ui/dom，以便两套 API 都可用', recommended: false },
    ],
    recommended: 'A',
  },
];
