/**
 * Isolated before/after comparison of the token sheets, between two commits.
 *
 * The Phase 0 baseline had a real weakness: it was taken from a working tree that also contained 71 unrelated
 * changes, so it proved the *integrated* tree worked, not that the token migration itself was value
 * preserving. Now that both states are commits, the comparison can be isolated: this tool loads the token
 * sheet out of a checked-out worktree of the "before" commit and out of the current tree, resolves every
 * token in every profile, and reports what actually moved.
 *
 * It needs no installed dependencies: it reads CSS through the repository's own resolver, so it can run
 * against an old commit whose package.json predates the current tooling.
 *
 * Usage: `node tools/baseline-diff.mjs --before <path-to-before/packages/tokens/src> [--write]`
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { AUDIT_PROFILES, PACKAGE_RENAMES } from './token-audit.pairs.mjs'
import { createResolver, loadTokenSheet } from './lib/css-tokens.mjs'

const BASELINE = '.spec-workflow/token-architecture/baseline.md'
const BEGIN = '<!-- BEGIN ISOLATED TOKEN DIFF (generated by tools/baseline-diff.mjs) -->'
const END = '<!-- END ISOLATED TOKEN DIFF -->'

/** The public entry of a token package, discovered rather than assumed: the layout changed in this work. */
export function findEntry(srcDir) {
  const candidates = ['index.css', 'tokens.css', 'all.css']
  for (const candidate of candidates) {
    const path = join(srcDir, candidate)
    if (existsSync(path)) return path
  }
  const root = readdirSync(srcDir).filter((name) => name.endsWith('.css'))
  if (root.length === 1) return join(srcDir, root[0])
  throw new Error(`baseline-diff: no entry found in ${srcDir} (candidates: ${root.join(', ')})`)
}

const describe = (dir) => {
  const files = []
  const walk = (current, depth) => {
    if (depth > 2) return
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      if (entry.isDirectory()) walk(join(current, entry.name), depth + 1)
      else if (entry.name.endsWith('.css')) files.push(join(current, entry.name))
    }
  }
  walk(dir, 0)
  return files
}

function resolveAll(srcDir) {
  const entry = findEntry(srcDir)
  const resolver = createResolver(loadTokenSheet({ entry }))
  const values = new Map()
  for (const profile of AUDIT_PROFILES) {
    for (const name of resolver.names(profile)) {
      const outcome = resolver.tryValue(name, profile)
      values.set(`${profile.id} ${name}`, outcome.ok ? outcome.value : `error: ${outcome.error}`)
    }
  }
  return { entry, values, files: describe(srcDir) }
}

const path = (await import('node:path')).posix
const args = process.argv.slice(2)
const beforeIndex = args.indexOf('--before')
if (beforeIndex === -1) {
  process.stderr.write('baseline-diff: --before <path> is required\n')
  process.exit(1)
}
const beforeSrc = args[beforeIndex + 1]
const afterSrc = 'packages/tokens/src'

const before = resolveAll(beforeSrc)
const after = resolveAll(afterSrc)

// A renamed token is compared under its new name: the register is the same mechanism the parity gate uses,
// so a rename does not read as a loss plus an addition.
const renamed = new Map(PACKAGE_RENAMES.map((entry) => [entry.prototype, entry.package]))
const beforeMapped = new Map()
for (const [key, value] of before.values) {
  const [profile, name] = key.split(' ')
  beforeMapped.set(`${profile} ${renamed.get(name) ?? name}`, value)
}

const keys = new Set([...beforeMapped.keys(), ...after.values.keys()])
const added = []
const lost = []
const changed = []
for (const key of [...keys].sort()) {
  const a = beforeMapped.get(key)
  const b = after.values.get(key)
  if (a === undefined) added.push(key)
  else if (b === undefined) lost.push(key)
  else if (a !== b) changed.push({ key, before: a, after: b })
}

const lines = [
  BEGIN,
  '',
  '### 隔离对比：改动前后两个提交的 Token 解析值',
  '',
  '由 `node tools/baseline-diff.mjs --before <checkout>/packages/tokens/src` 生成：',
  '把改动前的提交检出到独立 worktree，用**同一个解析器**读两侧的 Token 表，逐 profile 比较解析值。',
  '它只读 CSS，不需要安装依赖，因此可以在旧的 package.json 上运行。',
  '',
  `- 改动前入口：\`${before.entry}\`（${before.files.length} 个 CSS 文件）`,
  `- 改动后入口：\`${after.entry}\`（${after.files.length} 个 CSS 文件）`,
  `- 参与比较的 \`profile × token\`：${keys.size}`,
  `- 新增名字：${added.length}；消失名字：${lost.length}；解析值变化：${changed.length}`,
  '',
  '| 变化 | profile × token | 改动前 | 改动后 |',
  '| --- | --- | --- | --- |',
  ...added.slice(0, 40).map((key) => `| 新增 | \`${key}\` | — | ${after.values.get(key)} |`),
  ...lost.slice(0, 40).map((key) => `| 消失 | \`${key}\` | ${beforeMapped.get(key)} | — |`),
  ...changed.slice(0, 60).map((entry) => `| 值变化 | \`${entry.key}\` | ${entry.before} | ${entry.after} |`),
  '',
]
if (added.length > 40 || lost.length > 40 || changed.length > 60) {
  lines.push(`（表格已截断：新增 ${added.length}、消失 ${lost.length}、值变化 ${changed.length}）`, '')
}
lines.push(END, '')

const block = lines.join('\n')
if (args.includes('--write')) {
  const source = readFileSync(BASELINE, 'utf8')
  const pattern = new RegExp(`${BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`)
  writeFileSync(
    BASELINE,
    pattern.test(source) ? source.replace(pattern, block.trimEnd()) : `${source.trimEnd()}\n\n${block}`,
    'utf8',
  )
  console.log(`written into ${BASELINE}`)
}

console.log(`before: ${before.entry} (${before.files.length} css)`)
console.log(`after:  ${after.entry} (${after.files.length} css)`)
console.log(`added ${added.length}, lost ${lost.length}, changed ${changed.length}`)
for (const entry of changed.slice(0, 12)) console.log(`  ${entry.key}: ${entry.before} -> ${entry.after}`)
for (const key of added.slice(0, 6)) console.log(`  + ${key}`)
for (const key of lost.slice(0, 6)) console.log(`  - ${key}`)
