/**
 * Generate the rename migration table from `PACKAGE_RENAMES`.
 *
 * The register in `tools/token-audit.pairs.mjs` is the fact; prose tables are copies of facts, and copies
 * drift. So the table is generated into both the package README and the breaking-change record, between
 * markers, and `tests/rename-migration-table.test.mjs` fails when a copy stops matching the register.
 *
 * This also settles what "no aliases" means for consumers: the old name is *gone*, and the only supported
 * migration path is the new name — which is why the table has to be published rather than assumed.
 *
 * Usage: `node tools/rename-table.mjs` (rewrites the marked blocks in place; idempotent).
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'
import { PACKAGE_RENAMES } from './token-audit.pairs.mjs'

export const BEGIN = '<!-- BEGIN RENAME TABLE (generated by tools/rename-table.mjs) -->'
export const END = '<!-- END RENAME TABLE -->'

/** The table, in Chinese and English, generated from the register so it cannot disagree with the gates. */
export function renameTable(language = 'zh') {
  const header =
    language === 'zh'
      ? ['| 旧名（已移除） | 新名 | 理由 |', '| --- | --- | --- |']
      : ['| Old name (removed) | New name | Reason |', '| --- | --- | --- |']
  // The statement travels with the table: a generated table nobody explains is a table a consumer
  // misreads, and "no aliases" is only defensible when the replacement name is published.
  const lead =
    language === 'zh'
      ? [
          '#### 重命名迁移表（不保留 alias）',
          '',
          '旧名已从包中移除，**不保留 alias**：下表是唯一的迁移路径。本表由 `tools/rename-table.mjs`',
          '从 `PACKAGE_RENAMES` 生成，`tests/rename-migration-table.test.mjs` 要求它与注册表逐字一致。',
          '',
        ]
      : [
          '#### Rename migration table (no aliases)',
          '',
          'The old names are gone from the package and **no aliases are kept**: this table is the only',
          'migration path, generated by `tools/rename-table.mjs` from `PACKAGE_RENAMES`.',
          '',
        ]
  const reason = (entry) => entry.reason.replace(/\s+/g, ' ').trim()
  return [
    BEGIN,
    ...lead,
    ...header,
    ...PACKAGE_RENAMES.map((entry) => `| \`${entry.prototype}\` | \`${entry.package}\` | ${reason(entry)} |`),
    END,
  ].join('\n')
}

/** Replace the marked block, or insert it after `anchor` (a substring of an existing line). */
export function upsert(file, table, anchor) {
  const source = readFileSync(file, 'utf8')
  const pattern = new RegExp(`${BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`)
  if (pattern.test(source)) {
    writeFileSync(file, source.replace(pattern, table), 'utf8')
    return 'replaced'
  }
  const lines = source.split('\n')
  const index = lines.findIndex((line) => line.includes(anchor))
  if (index === -1) throw new Error(`${file}: anchor not found: ${anchor}`)
  lines.splice(index + 1, 0, '', table)
  writeFileSync(file, lines.join('\n'), 'utf8')
  return 'inserted'
}

const TARGETS = [
  { file: 'packages/tokens/README.md', language: 'zh', anchor: '名实背离' },
  { file: '.spec-workflow/token-architecture/breaking-changes.md', language: 'zh', anchor: '## ' },
]

// `pathToFileURL` rather than string concatenation: on Windows the drive form needs three slashes, and a
// two-slash comparison silently made this script a no-op.
if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  for (const target of TARGETS) {
    const action = upsert(target.file, renameTable(target.language), target.anchor)
    console.log(`${target.file}: ${action} ${PACKAGE_RENAMES.length} row(s)`)
  }
}
